---
##
# Configurations
##

##
# Clinical labels
##
clinical_labels:
  unknown: 'Unknown significance'
  pathogenic: 'Pathogenic'
  likely_pathogenic: 'Likely pathogenic'
  pred_pathogenic: 'Unknown significance'
  benign: 'Benign'
  likely_benign: 'Likely benign'
  pred_benign: 'Likely benign'

##
# Gene regions reference file
##
gene_regions_ref_file: '<PATH_TO_GENE_REGIONS_BED>'

##
# VCF annotation data files
##
annotation_files:
  clinvar: 
    include: true
    source: 'ClinVar'
    filename: '<PATH_TO_CLINVAR_VCF>' 
    fields:
      - 'CLINVAR_CLNSIG'      # Clinical significance
      - 'CLINVAR_DISEASE'     # Clinical disease name
      - 'CLINVAR_REVSTAT'     # Clinical review status
      - 'CLINVAR_PMID'        # PubMed IDs
      - 'CLINVAR_PATHOGENIC'  # At least 1 pathogenic call? (0 or 1)
      - 'CLINVAR_CONFLICTED'  # Any conflicting calls? (0 or 1)
  dbsnp:
    include: true
    source: 'dbSNP'
    filename: '<PATH_TO_DBSNP_VCF>'
    fields: !!null # Do not include any INFO fields (rsIDs only)
  dbnsfp:
    include: true
    source: 'dbNSFP'
    filename: '<PATH_TO_DBNSFP_BCF>'
    fields:
      - 'DBNSFP_SIFT_SCORE'
      - 'DBNSFP_SIFT_PRED'
      - 'DBNSFP_POLYPHEN2_HDIV_SCORE'
      - 'DBNSFP_POLYPHEN2_HDIV_PRED'
      - 'DBNSFP_LRT_SCORE'
      - 'DBNSFP_LRT_PRED'
      - 'DBNSFP_MUTATIONTASTER_SCORE'
      - 'DBNSFP_MUTATIONTASTER_PRED'
      - 'DBNSFP_GERP_RS'
      - 'DBNSFP_PHYLOP20WAY_MAMMALIAN'
  evs:
    include: true
    source: 'ESP6500'
    filename: '<PATH_TO_EVS_VCF>'
    fields:
      - 'EVS_EA_AC'  # European American alt allele counts
      - 'EVS_EA_AN'  # European American allele counts
      - 'EVS_EA_AF'  # European American allele frequency
      - 'EVS_AA_AC'  # African American alt allele counts
      - 'EVS_AA_AN'  # African American allele counts
      - 'EVS_AA_AF'  # African American allele frequency
      - 'EVS_ALL_AC' # Total alt allele counts
      - 'EVS_ALL_AN' # Total allele counts
      - 'EVS_ALL_AF' # Total allele frequency
  exac:
    include: true
    source: 'ExAC'
    filename: '<PATH_TO_EXAC_VCF>'
    fields:
      - 'EXAC_AFR_AC' # African American alt allele counts
      - 'EXAC_AFR_AN' # African American ref allele count
      - 'EXAC_AFR_AF' # African American allele frequency
      - 'EXAC_AMR_AC' # American alt allele counts
      - 'EXAC_AMR_AN' # American ref allele count
      - 'EXAC_AMR_AF' # American allele frequency
      - 'EXAC_EAS_AC' # East Asian alt allele counts
      - 'EXAC_EAS_AN' # East Asian ref allele count
      - 'EXAC_EAS_AF' # East Asian allele frequency
      - 'EXAC_FIN_AC' # European (Finnish) alt allele counts
      - 'EXAC_FIN_AN' # European (Finnish) ref allele count
      - 'EXAC_FIN_AF' # European (Finnish) allele frequency
      - 'EXAC_NFE_AC' # European (Non-Finnish) alt allele counts
      - 'EXAC_NFE_AN' # European (Non-Finnish) ref allele count
      - 'EXAC_NFE_AF' # European (Non-Finnish) allele frequency
      - 'EXAC_OTH_AC' # Other alt allele counts
      - 'EXAC_OTH_AN' # Other ref allele count
      - 'EXAC_OTH_AF' # Other allele frequency
      - 'EXAC_SAS_AC' # South Asian alt allele counts
      - 'EXAC_SAS_AN' # South Asian ref allele count
      - 'EXAC_SAS_AF' # South Asian allele frequency
      - 'EXAC_ALL_AC' # Total alt allele counts
      - 'EXAC_ALL_AN' # Total allele counts
      - 'EXAC_ALL_AF' # Total allele frequency
  hgmd:
    include: true
    source: 'HGMD'
    filename: '<PATH_TO_HGMD_VCF>'
    fields:
      - 'HGMD_VARIANTTYPE' # Type of variant (DM - disease-causing)
      - 'HGMD_DISEASE'     # Disease(s)
      - 'HGMD_CONFIDENCE'  # Pathogenicity confidence
      - 'HGMD_PMID'        # PubMed ID(s)
      - 'HGMD_OMIM_REF'    # OMIM phenotype ID(s)
  g1000:
    include: true
    source: '1KG'
    filename: '<PATH_TO_1KG_VCF>'
    fields:
      - '1KG_AFR_AC' # African American alt allele counts
      - '1KG_AFR_AN' # African American ref allele count
      - '1KG_AFR_AF' # African American allele frequency
      - '1KG_AMR_AC' # American alt allele counts
      - '1KG_AMR_AN' # American ref allele count
      - '1KG_AMR_AF' # American allele frequency
      - '1KG_EAS_AC' # East Asian alt allele counts
      - '1KG_EAS_AN' # East Asian ref allele count
      - '1KG_EAS_AF' # East Asian allele frequency
      - '1KG_EUR_AC' # European alt allele counts
      - '1KG_EUR_AN' # European ref allele count
      - '1KG_EUR_AF' # European allele frequency
      - '1KG_SAS_AC' # South Asian alt allele counts
      - '1KG_SAS_AN' # South Asian ref allele count
      - '1KG_SAS_AF' # South Asian allele frequency
      - '1KG_ALL_AC' # Total alt allele counts
      - '1KG_ALL_AN' # Total allele count
      - '1KG_ALL_AF' # Total allele frequency
  morl:
    include: true
    source: 'MORL'
    filename: '<PATH_TO_EXPERT_CURATION_VCF>'
    fields: '*' # Include all fields
  otoscope:
    include: true
    source: 'OtoSCOPE'
    filename: '<PATH_TO_OTODB_VCF>'
    fields: '*' # Include all fields

##
# Enable 'Benign*' (i.e. 'benign star')  pathogenicity label
#
# An asterisk (*) can be added to a benign label when the
# following two criteria are met:
# 1.) The variant is benign because it has a MAF that is greater
#     than or equal to the maximum allowed MAF.
# 2.) The variant is currently reported as pathogenic in ClinVar,
#     HGMD, or both.
##
enable_benign_star: true

##
# Third party dependencies
#
# Supply the full path to third party dependencies.
##
third_party:
  # ASAP annotation tool
  annotator: 'both'  # Which annotator to use. Options are "asap", "vep", and "both".
  asap:
    path: '<PATH_TO_ASAP_JAR>'
    ref_flat: '<PATH_TO_ASAP_REF_FLAT>'
    ref_seq_ali: '<PATH_TO_ASAP_REF_SEQ_ALI>'
    fasta: '<PATH_TO_FASTA>'
  #VEP annotation tool
  vep:
    path: '<PATH_TO_VEP>
    cache_path: '<PATH_TO_VEP_CACHE>
    config_path: '<KAFEEN_INSTALL>/config/vep_config.ini'
##
# Test
#
# Various configurations for testing
#
# Assertion tags
# - Define which INFO tags to do assertion testing on
# - For every tag in this list, a corresponding assert tag (e.g. 'ASSERT_GENE')
#   should be present in the input VCF
# - Assert tags in the input VCF should include the expected value
##
test:
  assertion_tags:
    - 'GENE'
    - 'DBNSFP_GERP_PRED'
    - 'DBNSFP_PHYLOP20WAY_MAMMALIAN_PRED'
    - 'NUM_PATH_PREDS'
    - 'TOTAL_NUM_PREDS'
    - 'FINAL_PRED'
    - 'FINAL_PATHOGENICITY'
    - 'FINAL_DISEASE'
    - 'FINAL_PATHOGENICITY_SOURCE'
    - 'FINAL_PMID'
    - 'FINAL_PATHOGENICITY_REASON'
    - 'FINAL_COMMENTS'
