require 'yaml'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  #   - http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/
  #   - http://www.teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
  #   - http://rspec.info/blog/2014/05/notable-changes-in-rspec-3/#zero-monkey-patching-mode
  config.disable_monkey_patching!

  # This setting enables warnings. It's recommended, but in some cases may
  # be too noisy due to issues in dependencies.
  config.warnings = true

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
end

# Set the application root for easy reference.
APP_ROOT = File.expand_path('../..', __FILE__)

# Load config file
CONFIG = YAML.load_file(File.join(APP_ROOT, 'config', 'config.yml'))

# VCF annotation files
VCF_FILES = CONFIG['annotation_files']

##
# No Output
#
# Suppress stdout during testing.
##
def no_output(&block)
  original_stdout = $stdout.dup
  $stdout.reopen('/dev/null')
  $stdout.sync = true
  begin
    yield
  ensure
    $stdout.reopen(original_stdout)
  end 
end

##
# Capture Output
#
# Capture stdout during testing.
##
def capture_output(&block)
  original_stdout = $stdout.dup
  output_catcher = StringIO.new
  $stdout = output_catcher
  begin
    yield
  ensure
    $stdout = original_stdout
  end 
  output_catcher.string
end

##
# Setup Fake Input
##
def setup_fake_input(*args)
  allow(Readline).to receive(:readline).and_return(*args)
end

##
# Remove Created Files
#
# Clean up by deleting created files.
##
def remove_created_files(*args)
  args.each do |file_path|
    if file_path && File.exists?(file_path)
      File.delete(file_path)
    end 
  end 
end

##
# Select Keys
#
# Subset a hash by selecting specific keys (i.e. remove key-value
# pairs from a hash by selection which keys you would like to keep).
##
class Hash
  # Taken from:
  # https://stackoverflow.com/a/6620079/990637
  def select_keys(*args)
    select {|k,v| args.include?(k) }
  end
end

##
# Subset Variants From VCF
#
# Subset a VCF file to only include CHROM, POS, REF, and ALT in TSV format.
# Add additional tags using the 'tags' option (tags separated by commas). Add
# exclusions to the query using the 'exclude' option. Exclusions separated by
# '&&' or '||' and may not include single quotes.
#
# Example usage:
#   subset_variants_from_VCF(f_in: 'in.vcf.gz', f_out: 'out.tsv'
#                            tags: '1KG_ALL_AF,EXAC_ALL_AF',
#                            exclude: '1KG_ALL_AF == "." && EXAC_ALL_AF == "."')
##
def subset_variants_from_vcf(f_in:, f_out:, tags: '', exclude: '')
  raise SyntaxError, "'exclude' cannot include single-quotes" if exclude.include?("'")

  # Convert tags from comma-sep. to tab-sep. for bcftools
  if !tags.empty?
    tags = tags.sub(/^/, "\t%").gsub(/,/, "\t%")
  end

  # Format exclusion option
  if !exclude.empty?
    exclude = "-e '#{exclude}'"
  end

  # Subset GJB2 test set
  `bcftools query #{exclude} -f '%CHROM\t%POS\t%REF\t%ALT#{tags}\n' #{f_in} \
     | sort -u -k2,2n -k43,3d -k4,4d \
     > #{f_out}`
end
